# Config dedicated for module B
# All the resources must be prefixed with `module-b-` to avoid conflicts

orbs:
  module-b-hello-build: circleci/hello-build@0.0.14

jobs:
  module-b-build:
    docker:
      - image: alpine
    steps:
      - common-say-hello:
          to: B
      - run: echo 'Hello, from module B! :3'

workflows:
  module-a-b:
    # when: << pipeline.parameters.run-module-b >>
    jobs:
      - module-a-build
      - module-b-build:
          requires:
            - module-a-build