# Config dedicated for module B
# All the resources must be prefixed with `module-b-` to avoid conflicts 

version: 2.1

# Anchors
defaults: &defaults
  executor:
    name: node/default
    tag: 'lts'


orbs:
  node: circleci/node@2.1
  module-b-hello-build: circleci/hello-build@0.0.14

jobs:
  module-b-build:
    docker:
      - image: alpine
    steps:
      - run: echo 'Hello, from module B! :3'
  module-b-build-and-publish:
    <<: *defaults
    steps:
      - run: echo '[B] RUN module-b-build-and-publish !!!'
  module-b-deploy-storybook:
    <<: *defaults
    steps:
      - run: echo '[B] RUN module-b-deploy-storybook !!!'

workflows:
  # module-a-b:
    # when: << pipeline.parameters.run-module-b >>
  #  jobs:
  #    - module-a-build
  #    - module-b-build:
  #        requires:
  #          - module-a-build
  build:
    jobs:
      - module-b-build-and-publish:
          requires:
            - module-b-build-and-publish
          filters:
            tags:
              only: /^v.*/
      - module-b-deploy-storybook:
          requires:
            - module-b-build-and-publish
          filters:
            branches:
              only: master2