# Config dedicated for module B
# All the resources must be prefixed with `module-b-` to avoid conflicts 

version: 2.1

# Anchors
defaults: &defaults
  executor:
    name: node/default
    tag: 'lts'


orbs:
  node: circleci/node@2.1
  module-b-hello-build: circleci/hello-build@0.0.14

jobs:
  module-b-build:
    docker:
      - image: alpine
    steps:
      - run: echo 'Hello, from module B! :3'
  module-b-build-and-publish:
    <<: *defaults
    working_directory: ~/jmlpoc/module-b
    steps:
      - checkout:
          path: ~/jmlpoc # Root of the project
      - run: yarn
      - run: yarn prebuild
      - run: echo '[B] RUN module-b-build-and-publish !!!'
      - run:
          name: Publish Module-B
          command: |
            cd module-b
            bash ./publish.sh
  module-b-deploy-storybook:
    <<: *defaults
    steps:
      - run: echo '[B] RUN module-b-deploy-storybook  !!! '

workflows:
  module-workflow:
    jobs:
      - module-b-build-and-publish:
          requires:
            - module-a-build-and-publish
          filters:
            tags:
              only: /^v.*/
      - module-b-deploy-storybook:
          requires:
            - module-b-build-and-publish
          filters:
            branches:
              only: master3