# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts

version: 2.1

# Anchors
defaults: &defaults
  executor:
    name: node/default
    tag: 'lts'

orbs:
  node: circleci/node@2.1
  # Note: We are using the latest version of hello-build, whereas module B uses an older one
  module-a-hello-build: circleci/hello-build@0.0.14

jobs:
  #module-a-build:
  #  docker:
  #    - image: alpine
  #  steps:
  #    - run: echo 'Hello world from module A! :3'
  module-a-build-and-publish:
    <<: *defaults
    steps:
      - run: echo '[A] RUN module-a-build-and-publish !!!'
  module-a-deploy-storybook:
    <<: *defaults
    steps:
      - run: echo '[A] RUN module-a-deploy-storybook !!!'
  module-a-deploy-cdn:
    <<: *defaults
    steps:
      - run: echo '[A] RUN module-a-deploy-cdn !!!'

workflows:
  module-workflow:
    jobs:
      - module-a-build-and-publish:
          filters:
            tags:
              only: /^v.*$/
      - module-a-deploy-storybook:
          requires:
            - module-a-build-and-publish
          filters:
            branches:
              only: master2
      - module-a-deploy-cdn:
          #cdn_version_path: << pipeline.git.tag >>
          requires:
            - module-a-build-and-publish
          filters:
            branches:
              only: master2
            tags:
              only: /^v.*\d$(?!^v.*SNAPSHOT.*$)/