version: 2.1

setup: << pipeline.parameters.run-setup >>

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.2.0

parameters:
  run-setup:
    type: boolean
    default: true
  run-module-a:
    type: boolean
    default: false
  run-module-b:
    type: boolean
    default: false

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout # checkout code
      - run: # run a command
          name: Generate config
          command: |
            cat module-a/.circleci/config.yml module-b/.circleci/config.yml > .circleci/generated_config.yml
      - run: cat .circleci/generated_config.yml
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml # use newly generated config to continue
          parameters: "{'run-module-b': 'true'}"
  module-a:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: "echo 'Hello from module A!'"
      - run: cat module-a/README.md

  module-b:
    machine: true
    steps:
      - checkout
      - run: "echo 'Hello from module B!'"
      - run: cat module-b/README.md

  module-b-post:
    docker:
      - image: alpine
    steps:
      - run: "echo 'Continuing module B'"
      - run: env

workflows:
  setup:
    jobs:
      - setup
  module-a:
    when: << pipeline.parameters.run-module-a >>
    jobs:
      - module-a
#  module-b:
#    when: << pipeline.parameters.run-module-b >>
#    jobs:
#      - module-b:
#          requires:
#            - module-a
#      - module-b-post:
#          requires:
#            - module-b
  module-a-b:
    when: << pipeline.parameters.run-module-b >>
    jobs:
      - module-a
      - module-b:
          requires:
            - module-a
